# Generated by Django 2.0.6 on 2018-06-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('car_number', models.IntegerField()),
                ('cost_event', models.DecimalField(decimal_places=2, max_digits=5)),
                ('design_event', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sales_presentation', models.DecimalField(decimal_places=2, max_digits=4)),
                ('acceleration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('maneuverability', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hill_climb', models.DecimalField(decimal_places=2, max_digits=4)),
                ('suspension', models.DecimalField(decimal_places=2, max_digits=4)),
                ('endurance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('penalties', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
