# Generated by Django 2.0.6 on 2018-06-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20180615_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='endurancelaps',
            new_name='endurance',
        ),
    ]
